apiVersion: v1
kind: Service
metadata:
  name: oci-monitoring-api
  labels:
    app: oci-monitoring-api
spec:
  type: ClusterIP
  selector:
    app: oci-monitoring-api
  ports:
    - name: http
      port: 5005
      targetPort: 5005
